export type Channel = "whatsapp";
export type LabelColor = "indigo" | "pink" | "emerald" | "amber" | "sky" | "violet" | "slate";

export const LIFECYCLE_STAGES = [
  "New Lead",
  "Contacted",
  "Qualified",
  "Pending Payment",
  "Customer",
  "Lost",
  "No Reply",
] as const;
export type LifecycleStage = string;

export const PROGRESSING_STAGES: string[] = [
  "New Lead",
  "Contacted",
  "Qualified",
  "Pending Payment",
  "Customer",
];
export const LOST_STAGES: string[] = ["Lost", "No Reply"];

export const STAGE_COLORS: Record<string, { bar: string; dot: string; badge: string }> = {
  "New Lead": {
    bar: "bg-orange-500",
    dot: "bg-orange-500",
    badge: "border-orange-500/30 bg-orange-500/10 text-orange-300",
  },
  Contacted: {
    bar: "bg-blue-500",
    dot: "bg-blue-500",
    badge: "border-blue-500/30 bg-blue-500/10 text-blue-300",
  },
  Qualified: {
    bar: "bg-purple-500",
    dot: "bg-purple-500",
    badge: "border-purple-500/30 bg-purple-500/10 text-purple-300",
  },
  "Pending Payment": {
    bar: "bg-yellow-500",
    dot: "bg-yellow-500",
    badge: "border-yellow-500/30 bg-yellow-500/10 text-yellow-300",
  },
  Customer: {
    bar: "bg-green-500",
    dot: "bg-green-500",
    badge: "border-green-500/30 bg-green-500/10 text-green-300",
  },
  Lost: {
    bar: "bg-red-500",
    dot: "bg-red-500",
    badge: "border-red-500/30 bg-red-500/10 text-red-300",
  },
  "No Reply": {
    bar: "bg-gray-500",
    dot: "bg-gray-500",
    badge: "border-gray-500/30 bg-gray-500/10 text-gray-300",
  },
};

export type ContactLabel = {
  id: string;
  name: string;
  color: LabelColor;
};

export type ContactList = {
  id: string;
  name: string;
  description?: string;
};

export type Contact = {
  id: string;
  name: string;
  phone: string;
  email?: string;
  instagram?: string;
  channel: Channel;
  labelIds: string[];
  listIds: string[];
  brandIds: string[];
  lastInteraction: string;
  status: "Active" | "Inactive" | "Blocked";
  avatar: string;
  gender?: "Female" | "Male" | "Other";
  ownerId?: string;
  lifecycleStage?: string;
  stageEnteredAt?: string;
  customFields?: Record<string, unknown>;
  deleted?: boolean;
  deletedAt?: string;
  pointBalance?: number;
};

const avatars = [
  "PA",
  "BP",
  "SR",
  "DL",
  "RM",
  "IP",
  "AS",
  "MK",
  "CH",
  "RW",
  "BH",
  "NS",
  "AF",
  "YP",
  "TH",
  "LW",
  "GS",
  "NK",
  "FR",
  "ZA",
  "MR",
  "DP",
  "HS",
  "IA",
  "WS",
  "KN",
  "SB",
  "RP",
  "OL",
  "EM",
  "MH",
  "FA",
  "NP",
  "BR",
  "CS",
  "AW",
  "FN",
  "DK",
];

export const initialLabels: ContactLabel[] = [
  { id: "lb-vip", name: "VIP Customer", color: "amber" },
  { id: "lb-beauty-club", name: "Beauty Club", color: "pink" },
  { id: "lb-reseller", name: "Reseller", color: "indigo" },
  { id: "lb-ba", name: "Beauty Ambassador", color: "violet" },
  { id: "lb-team", name: "Internal Team", color: "slate" },
];

export const initialLists: ContactList[] = [
  { id: "ls-vip", name: "VIP Customers", description: "Top loyalty tier members" },
  { id: "ls-jakarta", name: "Customers — Jakarta", description: "Tunjungan Plaza & PIM stores" },
  { id: "ls-bandung", name: "Customers — Bandung", description: "Paris van Java & TSM stores" },
  { id: "ls-launch", name: "Product Launch Audience", description: "Opted-in to new SKU launches" },
  { id: "ls-community", name: "Aroma Beauty Club", description: "WhatsApp loyalty community" },
];

export const contacts: Contact[] = [
  // ── Customer Contacts ──────────────────────────────────────────────
  {
    id: "c1",
    name: "Putri Anggraini",
    phone: "+62 812 3456 7890",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-vip", "lb-beauty-club"],
    listIds: ["ls-vip", "ls-launch"],
    brandIds: ["brand-sisley", "brand-dg"],
    lastInteraction: "2m ago",
    status: "Active",
    avatar: avatars[0],
    ownerId: "arma",
    pointBalance: 4820,
  },
  {
    id: "c2",
    name: "Bagus Pratama",
    phone: "+62 813 2244 5566",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-reseller"],
    listIds: ["ls-launch"],
    brandIds: ["brand-rimmel"],
    lastInteraction: "11m ago",
    status: "Active",
    avatar: avatars[1],
    ownerId: "arma",
    pointBalance: 1250,
  },
  {
    id: "c3",
    name: "Siti Rahmawati",
    phone: "+62 821 9988 7766",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-vip"],
    listIds: ["ls-vip", "ls-jakarta"],
    brandIds: ["brand-sisley"],
    lastInteraction: "32m ago",
    status: "Active",
    avatar: avatars[2],
    ownerId: "arma",
    pointBalance: 3670,
  },
  {
    id: "c5",
    name: "Rizky Maulana",
    phone: "+62 822 3344 7788",
    channel: "whatsapp",
    gender: "Male",
    labelIds: [],
    listIds: ["ls-community"],
    brandIds: ["brand-bm"],
    lastInteraction: "2h ago",
    status: "Active",
    avatar: avatars[4],
    ownerId: "arma",
    pointBalance: 580,
  },
  {
    id: "c6",
    name: "Indah Permata",
    phone: "+62 815 7788 9900",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-vip"],
    listIds: ["ls-vip", "ls-community"],
    brandIds: ["brand-dg", "brand-sisley"],
    lastInteraction: "3h ago",
    status: "Active",
    avatar: avatars[5],
    ownerId: "arma",
    pointBalance: 7200,
  },
  {
    id: "c7",
    name: "Andika Saputra",
    phone: "+62 818 4422 1133",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-reseller"],
    listIds: ["ls-jakarta"],
    brandIds: ["brand-rimmel"],
    lastInteraction: "5h ago",
    status: "Active",
    avatar: avatars[6],
    ownerId: "arma",
    pointBalance: 990,
  },
  {
    id: "c9",
    name: "Citra Halim",
    phone: "+62 856 1122 3344",
    channel: "whatsapp",
    gender: "Female",
    labelIds: [],
    listIds: ["ls-launch", "ls-community"],
    brandIds: ["brand-laura"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[8],
    ownerId: "arma",
    pointBalance: 2100,
  },
  {
    id: "c11",
    name: "Bayu Hartanto",
    phone: "+62 858 5544 3322",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-vip", "lb-reseller"],
    listIds: ["ls-vip", "ls-jakarta"],
    brandIds: ["brand-sisley", "brand-rimmel"],
    lastInteraction: "3d ago",
    status: "Active",
    avatar: avatars[10],
    ownerId: "arma",
    pointBalance: 5430,
  },
  {
    id: "c12",
    name: "Nadya Salsabila",
    phone: "+62 877 2211 4455",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-beauty-club"],
    listIds: ["ls-bandung", "ls-launch"],
    brandIds: ["brand-laura"],
    lastInteraction: "4d ago",
    status: "Active",
    avatar: avatars[11],
    ownerId: "arma",
    pointBalance: 1880,
  },
  {
    id: "c13",
    name: "Ayu Fitriani",
    phone: "+62 812 8877 6655",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-vip"],
    listIds: ["ls-vip", "ls-jakarta"],
    brandIds: ["brand-dg"],
    lastInteraction: "1h ago",
    status: "Active",
    avatar: avatars[12],
    ownerId: "arma",
    pointBalance: 3200,
  },
  {
    id: "c14",
    name: "Yusuf Priyanto",
    phone: "+62 821 3322 9988",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-reseller"],
    listIds: ["ls-launch"],
    brandIds: ["brand-rimmel"],
    lastInteraction: "3h ago",
    status: "Active",
    avatar: avatars[13],
    ownerId: "arma",
    pointBalance: 760,
  },
  {
    id: "c15",
    name: "Tiara Hapsari",
    phone: "+62 857 4411 0022",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-beauty-club"],
    listIds: ["ls-community", "ls-launch"],
    brandIds: ["brand-sisley"],
    lastInteraction: "5h ago",
    status: "Active",
    avatar: avatars[14],
    ownerId: "arma",
    pointBalance: 2340,
  },
  {
    id: "c16",
    name: "Lina Wulandari",
    phone: "+62 813 6655 4433",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-vip", "lb-beauty-club"],
    listIds: ["ls-vip", "ls-community"],
    brandIds: ["brand-dg", "brand-laura"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[15],
    ownerId: "arma",
    pointBalance: 6100,
  },
  {
    id: "c17",
    name: "Galih Santoso",
    phone: "+62 878 9900 1122",
    channel: "whatsapp",
    gender: "Male",
    labelIds: [],
    listIds: ["ls-jakarta"],
    brandIds: ["brand-bm"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[16],
    ownerId: "arma",
    pointBalance: 420,
  },
  {
    id: "c18",
    name: "Nita Kurniasari",
    phone: "+62 822 7788 5566",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-beauty-club"],
    listIds: ["ls-bandung", "ls-community"],
    brandIds: ["brand-sisley"],
    lastInteraction: "2d ago",
    status: "Active",
    avatar: avatars[17],
    ownerId: "arma",
    pointBalance: 1560,
  },
  {
    id: "c19",
    name: "Fajar Ramadhan",
    phone: "+62 819 5544 3311",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-reseller"],
    listIds: ["ls-launch", "ls-jakarta"],
    brandIds: ["brand-rimmel"],
    lastInteraction: "2d ago",
    status: "Active",
    avatar: avatars[18],
    ownerId: "arma",
    pointBalance: 870,
  },
  {
    id: "c20",
    name: "Zahra Aulia",
    phone: "+62 856 0011 2233",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-vip"],
    listIds: ["ls-vip"],
    brandIds: ["brand-dg"],
    lastInteraction: "3d ago",
    status: "Active",
    avatar: avatars[19],
    ownerId: "arma",
    pointBalance: 4100,
  },
  {
    id: "c21",
    name: "Mira Rahmawati",
    phone: "+62 815 4455 8899",
    channel: "whatsapp",
    gender: "Female",
    labelIds: [],
    listIds: ["ls-community"],
    brandIds: ["brand-laura"],
    lastInteraction: "3d ago",
    status: "Active",
    avatar: avatars[20],
    ownerId: "arma",
    pointBalance: 290,
  },
  {
    id: "c22",
    name: "Dian Puspita",
    phone: "+62 877 6677 3344",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-beauty-club"],
    listIds: ["ls-bandung"],
    brandIds: ["brand-sisley"],
    lastInteraction: "4d ago",
    status: "Active",
    avatar: avatars[21],
    ownerId: "arma",
    pointBalance: 1730,
  },

  // ── BA Contacts ────────────────────────────────────────────────────
  {
    id: "c4",
    name: "Dewi Lestari",
    phone: "+62 811 5566 1122",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-sisley"],
    lastInteraction: "1h ago",
    status: "Active",
    avatar: avatars[3],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c8",
    name: "Maya Kusuma",
    phone: "+62 819 6655 2244",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-dg"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[7],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c10",
    name: "Reza Wijaya",
    phone: "+62 857 8899 0011",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-rimmel"],
    lastInteraction: "2d ago",
    status: "Active",
    avatar: avatars[9],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c23",
    name: "Hesti Andriani",
    phone: "+62 811 2233 4455",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-laura"],
    lastInteraction: "30m ago",
    status: "Active",
    avatar: avatars[22],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c24",
    name: "Indra Wahyudi",
    phone: "+62 821 8877 6655",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-bm"],
    lastInteraction: "1h ago",
    status: "Active",
    avatar: avatars[23],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c25",
    name: "Wulan Sari",
    phone: "+62 857 3344 5566",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-dg"],
    lastInteraction: "2h ago",
    status: "Active",
    avatar: avatars[24],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c26",
    name: "Kevin Nugroho",
    phone: "+62 812 9900 8877",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-sisley"],
    lastInteraction: "4h ago",
    status: "Active",
    avatar: avatars[25],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c27",
    name: "Sinta Bella",
    phone: "+62 819 1122 7788",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-rimmel"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[26],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c28",
    name: "Rizal Pratama",
    phone: "+62 878 5566 4433",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-laura"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[27],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c29",
    name: "Olivia Lim",
    phone: "+62 813 3344 9900",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-bm"],
    lastInteraction: "2d ago",
    status: "Active",
    avatar: avatars[28],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c30",
    name: "Eka Marlinda",
    phone: "+62 856 7788 1122",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-dg", "brand-sisley"],
    lastInteraction: "2d ago",
    status: "Active",
    avatar: avatars[29],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c31",
    name: "Mia Hartanti",
    phone: "+62 812 1100 2233",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-sisley"],
    lastInteraction: "45m ago",
    status: "Active",
    avatar: avatars[30],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c32",
    name: "Fauzan Akbar",
    phone: "+62 821 4455 6677",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-rimmel"],
    lastInteraction: "2h ago",
    status: "Active",
    avatar: avatars[31],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c33",
    name: "Nadia Pramesti",
    phone: "+62 857 9988 1100",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-laura"],
    lastInteraction: "3h ago",
    status: "Active",
    avatar: avatars[32],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c34",
    name: "Bintang Ramadan",
    phone: "+62 813 5544 7788",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-bm"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[33],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c35",
    name: "Clara Santika",
    phone: "+62 878 2211 3344",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-dg"],
    lastInteraction: "Yesterday",
    status: "Active",
    avatar: avatars[34],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c36",
    name: "Ariel Wijaya",
    phone: "+62 812 6677 8899",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-sisley"],
    lastInteraction: "2d ago",
    status: "Active",
    avatar: avatars[35],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c37",
    name: "Fina Rahayu",
    phone: "+62 819 3322 5566",
    channel: "whatsapp",
    gender: "Female",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-rimmel", "brand-laura"],
    lastInteraction: "2d ago",
    status: "Active",
    avatar: avatars[36],
    ownerId: "arma",
    pointBalance: 0,
  },
  {
    id: "c38",
    name: "Dodi Kurnia",
    phone: "+62 856 4433 9900",
    channel: "whatsapp",
    gender: "Male",
    labelIds: ["lb-ba"],
    listIds: [],
    brandIds: ["brand-bm"],
    lastInteraction: "3d ago",
    status: "Active",
    avatar: avatars[37],
    ownerId: "arma",
    pointBalance: 0,
  },
];

export type Message = {
  id: string;
  from: "them" | "me";
  text: string;
  time: string;
  status?: "sent" | "delivered" | "read";
  // Who authored this outgoing ("me") message — Arma's autopilot or a
  // teammate after taking over. Irrelevant for incoming ("them") messages.
  sentBy?: "arma" | "human";
};

export const threadsByContact: Record<string, Message[]> = {
  c1: [
    {
      id: "m1",
      from: "them",
      text: "Halo kak! Lipstick Velvet Rouge shade 03 ready stock ga?",
      time: "10:22",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Halo Putri! Shade 03 baru restock pagi ini. Mau aku reserve satu?",
      time: "10:23",
      status: "read",
    },
    {
      id: "m3",
      from: "them",
      text: "Mau dong 🙏 boleh pakai diskon Beauty Club ku?",
      time: "10:24",
    },
    {
      id: "m4",
      from: "me",
      sentBy: "arma",
      text: "Sudah diaplikasikan. Link checkout privat: aroma.id/v/putri-22",
      time: "10:25",
      status: "read",
    },
    { id: "m5", from: "them", text: "Makasih banyak! Aku checkout sekarang ya.", time: "10:26" },
  ],
  c2: [
    {
      id: "m1",
      from: "them",
      text: "Min, untuk reseller Glow Serum minimum order berapa pcs?",
      time: "09:48",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Halo Bagus! Mulai 24 pcs untuk harga reseller. Aku kirim katalognya ya.",
      time: "09:50",
      status: "delivered",
    },
  ],
  c3: [
    {
      id: "m1",
      from: "them",
      text: "Mau pesan hampers Lebaran 120 pax untuk karyawan kami.",
      time: "Yesterday",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Siap! Aku kirim katalog corporate + harga bulk sekarang.",
      time: "Yesterday",
      status: "read",
    },
    { id: "m3", from: "them", text: "Oke, aku loop in tim procurement kami.", time: "Yesterday" },
  ],
  // BA Inbox threads
  c4: [
    {
      id: "m1",
      from: "them",
      text: "Halo Arma! Gimana cara handle customer yang tanya perbedaan Sisley vs Rimmel?",
      time: "13:10",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Halo Dewi! Sisley lebih premium & fokus ke skincare-makeup hybrid, cocok untuk kulit mature. Rimmel lebih playful & terjangkau, target younger crowd. Kalau customernya 25–35 tahun, sarankan Sisley untuk daily luxury. Mau script lengkapnya?",
      time: "13:12",
      status: "read",
    },
    { id: "m3", from: "them", text: "Mau dong Arma, makasih banyak!", time: "13:13" },
  ],
  c8: [
    {
      id: "m1",
      from: "them",
      text: "Arma tolong jelasin kandungan Glow Serum buat aku presentasiin ke customer.",
      time: "Yesterday",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Glow Serum mengandung: Niacinamide 5% (pori-pori & cerah), Hyaluronic Acid (hidrasi), Vitamin C stabilized (antioksidan), dan Peptide Complex (anti-aging). Key selling point: cocok untuk semua skin type, non-comedogenic, hasil terlihat dalam 2 minggu.",
      time: "Yesterday",
      status: "read",
    },
  ],
  c23: [
    {
      id: "m1",
      from: "them",
      text: "Arma, shade berapa yang paling laris bulan ini?",
      time: "14:30",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Bulan ini top seller: Velvet Rouge Shade 03 (Rosewood), Shade 07 (Burgundy), dan Shade 11 (Nude Mauve). Shade 03 paling cepat habis, stok di gudang tinggal 48 pcs.",
      time: "14:31",
      status: "read",
    },
    {
      id: "m3",
      from: "them",
      text: "Oke noted! Aku rekomendasi yang itu dulu ke customer.",
      time: "14:32",
    },
  ],
  c24: [
    {
      id: "m1",
      from: "them",
      text: "Cara jelasin benefit Laura Mercier ke customer baru gimana Arma?",
      time: "13:45",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Untuk customer baru Laura Mercier: fokus pada 3 hal — (1) iconic Translucent Setting Powder yang viral, (2) Kaviar Stick untuk on-the-go touch up, (3) Flawless Lumiere Foundation yang buildable. Opening yang works: 'Kalau mau tampilan natural tapi tahan lama, Laura Mercier adalah jawabannya.'",
      time: "13:47",
      status: "delivered",
    },
  ],
  c27: [
    {
      id: "m1",
      from: "them",
      text: "Diskon event 12.12 berlaku untuk produk apa aja Arma?",
      time: "Yesterday",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "12.12 berlaku untuk semua SKU kecuali limited edition & new arrival (< 30 hari). Diskon: 20% untuk single item, 30% untuk bundle 3 produk. Kode promo: ARMA1212. Valid 12 Des 00:00–23:59.",
      time: "Yesterday",
      status: "read",
    },
    {
      id: "m3",
      from: "them",
      text: "Siap Arma! Aku info ke semua customer aku.",
      time: "Yesterday",
    },
  ],
  c31: [
    {
      id: "m1",
      from: "them",
      text: "Arma, ada tips untuk upsell ke customer yang udah beli foundation?",
      time: "45m",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Teknik upsell paling efektif: tawarkan setting powder + brush set sebagai 'completing the look'. Bundle harga juga works — kalau customer udah beli foundation Sisley, tawarkan Sisley Skincare untuk prep sebelum makeup.",
      time: "43m",
      status: "delivered",
    },
  ],
  c32: [
    {
      id: "m1",
      from: "them",
      text: "Gimana cara jelasin perbedaan Rimmel Stay Matte vs Lasting Finish ke customer?",
      time: "2h",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Stay Matte: matte finish, cocok kulit berminyak, coverage medium. Lasting Finish: lebih buildable, semi-matte, tahan 25 jam. Customer dengan kombinasi skin → Lasting Finish. Kulit oily → Stay Matte.",
      time: "1h 58m",
      status: "read",
    },
    { id: "m3", from: "them", text: "Oke thanks Arma! Berguna banget.", time: "1h 55m" },
  ],
  c33: [
    {
      id: "m1",
      from: "them",
      text: "Arma, stok Laura Mercier Translucent Powder kapan restocknya?",
      time: "3h",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Restock dijadwalkan minggu depan. Aku sudah masukkan nama kamu di waitlist notif. Untuk customer yang minta, bisa tawarkan Laura Mercier Loose Setting Powder sebagai alternatif sementara.",
      time: "2h 58m",
      status: "read",
    },
  ],
  c34: [
    {
      id: "m1",
      from: "them",
      text: "Script untuk handle customer yang complain warna bareMinerals tidak sesuai foto?",
      time: "Yesterday",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Gunakan script ini: 'Terima kasih feedbacknya! Warna mineral makeup memang bisa terlihat berbeda tergantung pencahayaan & undertone kulit. Boleh saya bantu carikan shade yang lebih pas dengan skin tone kamu?' Tawarkan swatch test jika di store.",
      time: "Yesterday",
      status: "read",
    },
    { id: "m3", from: "them", text: "Perfect, aku save dulu ya Arma.", time: "Yesterday" },
  ],
  c35: [
    {
      id: "m1",
      from: "them",
      text: "Cara presentasi Dior Beauty ke customer baru yang belum familiar gimana Arma?",
      time: "Yesterday",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Opening yang works: 'Dior Beauty bukan sekedar makeup — ini adalah art. Setiap produk dirancang oleh creative director Dior untuk menonjolkan keindahan natural kamu.' Fokus pada 3 hero product: Rouge Dior Lipstick, Backstage Foundation, Airflash Setting Spray.",
      time: "Yesterday",
      status: "delivered",
    },
  ],
  c36: [
    {
      id: "m1",
      from: "them",
      text: "Arma ada SOP untuk handling retur produk Sisley di store?",
      time: "2d",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "SOP retur Sisley: (1) Cek struk & kondisi produk, (2) Jika < 7 hari & sealed → full refund, (3) Jika sudah dibuka → exchange atau store credit, (4) Foto kondisi produk sebelum proses. Lapor ke supervisor jika nilai > 500rb.",
      time: "2d",
      status: "read",
    },
  ],
  c37: [
    {
      id: "m1",
      from: "them",
      text: "Berapa target penjualan per bulan untuk BA level junior Arma?",
      time: "2d",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Target BA Junior: Rp 15–20 juta/bulan. Target BA Regular: Rp 25–35 juta/bulan. Senior BA: Rp 40–60 juta/bulan. Supervisor: Rp 75 juta+/bulan. Bonus berlaku jika melebihi target 10%.",
      time: "2d",
      status: "read",
    },
    { id: "m3", from: "them", text: "Noted Arma, makasih infonya!", time: "2d" },
  ],
  c38: [
    {
      id: "m1",
      from: "them",
      text: "Cara demo aplikasi bareMinerals yang bener ke customer gimana?",
      time: "3d",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Demo bareMinerals: (1) Mulai dengan Prep Step Primer, (2) Swirl-tap-buff foundation dengan kabuki brush gerakan melingkar, (3) Highlight dengan Luminizer, (4) Set dengan Mineral Veil. Key message: bebas paraben, cocok untuk sensitive skin.",
      time: "3d",
      status: "read",
    },
  ],
  c10: [
    {
      id: "m1",
      from: "them",
      text: "Script untuk closing customer yang masih ragu-ragu ada ga Arma?",
      time: "2d",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Coba script ini: 'Saya paham kamu masih pertimbangkan. Rimmel Stay Matte ini best seller kami karena hasil matte-nya tahan seharian bahkan di cuaca panas. Kalau mau, aku bisa bantu pilih shade yang paling cocok untuk skin tone kamu.' Fokus pada social proof + personalisasi.",
      time: "2d",
      status: "read",
    },
    { id: "m3", from: "them", text: "Oke mantap, aku coba script itu!", time: "2d" },
  ],
  c25: [
    {
      id: "m1",
      from: "them",
      text: "Arma ada template follow-up untuk customer yang belum checkout?",
      time: "2h",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Pakai template ini: 'Halo [nama]! Kamu sempat lihat [produk DG/Dolce & Gabbana] kemarin. Stoknya terbatas nih — mau aku reserve dulu? Berlaku 24 jam 😊.' Kirim H+1 setelah mereka browse, open rate-nya tinggi banget.",
      time: "2h",
      status: "delivered",
    },
  ],
  c28: [
    {
      id: "m1",
      from: "them",
      text: "Arma, bedanya Laura Mercier Loose vs Pressed Setting Powder apa ya?",
      time: "Yesterday",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Loose Powder: lebih ringan, airbrush finish, ideal untuk bake technique & full coverage look. Pressed Powder: lebih travel-friendly, touch-up on-the-go, finish lebih natural. Customer yang aktif di luar → sarankan Pressed. Home/studio use → Loose.",
      time: "Yesterday",
      status: "read",
    },
    { id: "m3", from: "them", text: "Ngerti Arma, makasih penjelasannya!", time: "Yesterday" },
  ],
  c29: [
    {
      id: "m1",
      from: "them",
      text: "Arma, minimum stok di store berapa buat bareMinerals?",
      time: "2d",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Minimum stok bareMinerals per store: Original Foundation 6 SKU (masing-masing 3 pcs), Blush Color Infusion 4 variant (2 pcs each), Prep Step Primer 5 pcs, Mineral Veil 4 pcs. Total sekitar 30–35 pcs. Kalau stok < 50% trigger reorder ya.",
      time: "2d",
      status: "read",
    },
  ],
  c30: [
    {
      id: "m1",
      from: "them",
      text: "Arma, ada promo bundling Dior x Sisley ga bulan ini?",
      time: "2d",
    },
    {
      id: "m2",
      from: "me",
      sentBy: "arma",
      text: "Bulan ini belum ada bundling lintas brand. Yang ada: Sisley bundle — beli foundation + setting powder hemat 15%. Dior bundle — Rouge Dior + Backstage Foundation paket launch harga spesial. Kalau customer minta kombinasi keduanya, bisa custom quote ya.",
      time: "2d",
      status: "read",
    },
    { id: "m3", from: "them", text: "Oke Arma siap, makasih!", time: "2d" },
  ],
};

export type Conversation = {
  id: string;
  contactId: string;
  channel: Channel;
  preview: string;
  time: string;
  unread: number;
  pinned?: boolean;
};

export const conversations: Conversation[] = [
  // Consumer Inbox — transaksi & pembelian produk
  {
    id: "t1",
    contactId: "c1",
    channel: "whatsapp",
    preview: "Makasih banyak! Aku checkout sekarang ya.",
    time: "10:26",
    unread: 2,
    pinned: true,
  },
  {
    id: "t2",
    contactId: "c2",
    channel: "whatsapp",
    preview: "Min, untuk reseller Glow Serum minimum order…",
    time: "09:48",
    unread: 1,
  },
  {
    id: "t3",
    contactId: "c3",
    channel: "whatsapp",
    preview: "Oke, aku loop in tim procurement kami.",
    time: "Yesterday",
    unread: 0,
  },
  {
    id: "t5",
    contactId: "c5",
    channel: "whatsapp",
    preview: "Paket order #AA-82201 sudah sampai, makasih!",
    time: "2d",
    unread: 0,
  },
  {
    id: "t6",
    contactId: "c6",
    channel: "whatsapp",
    preview: "Ada diskon bundle Glow Set ga?",
    time: "2d",
    unread: 3,
  },
  {
    id: "t7",
    contactId: "c7",
    channel: "whatsapp",
    preview: "Besok aku kirim PO yang sudah ditandatangani.",
    time: "3d",
    unread: 0,
  },
  {
    id: "t13",
    contactId: "c13",
    channel: "whatsapp",
    preview: "Bisa COD kak untuk area Jakarta Selatan?",
    time: "1h",
    unread: 1,
  },
  {
    id: "t15",
    contactId: "c15",
    channel: "whatsapp",
    preview: "Mau order Glow Serum 3 botol, ada promo ga?",
    time: "5h",
    unread: 0,
  },
  {
    id: "t16",
    contactId: "c16",
    channel: "whatsapp",
    preview: "Sudah transfer ya kak, buktinya aku kirim.",
    time: "Yesterday",
    unread: 2,
  },
  {
    id: "t20",
    contactId: "c20",
    channel: "whatsapp",
    preview: "Velvet Rouge shade 07 ada stoknya kak?",
    time: "3d",
    unread: 0,
  },

  // BA Inbox — Beauty Ambassador bertanya tentang produk ke Arma
  {
    id: "t4",
    contactId: "c4",
    channel: "whatsapp",
    preview: "Arma, gimana cara handle customer yang tanya perbedaan Sisley vs Rimmel?",
    time: "1h",
    unread: 2,
  },
  {
    id: "t8",
    contactId: "c8",
    channel: "whatsapp",
    preview: "Arma tolong jelasin kandungan Glow Serum buat aku presentasiin ke customer.",
    time: "Yesterday",
    unread: 1,
  },
  {
    id: "t10",
    contactId: "c10",
    channel: "whatsapp",
    preview: "Script untuk closing customer yang masih ragu-ragu ada ga Arma?",
    time: "2d",
    unread: 0,
  },
  {
    id: "t23",
    contactId: "c23",
    channel: "whatsapp",
    preview: "Arma, shade berapa yang paling laris bulan ini?",
    time: "30m",
    unread: 3,
  },
  {
    id: "t24",
    contactId: "c24",
    channel: "whatsapp",
    preview: "Cara jelasin benefit Laura Mercier ke customer baru gimana?",
    time: "1h",
    unread: 1,
  },
  {
    id: "t25",
    contactId: "c25",
    channel: "whatsapp",
    preview: "Arma ada template follow-up untuk customer yang belum checkout?",
    time: "2h",
    unread: 0,
  },
  {
    id: "t27",
    contactId: "c27",
    channel: "whatsapp",
    preview: "Diskon event 12.12 berlaku untuk produk apa aja Arma?",
    time: "Yesterday",
    unread: 2,
  },
  {
    id: "t29",
    contactId: "c29",
    channel: "whatsapp",
    preview: "Arma, minimum stok di store berapa buat bareMinerals?",
    time: "2d",
    unread: 0,
  },
  {
    id: "t31",
    contactId: "c31",
    channel: "whatsapp",
    preview: "Arma, ada tips untuk upsell ke customer yang udah beli foundation?",
    time: "45m",
    unread: 1,
  },
  {
    id: "t32",
    contactId: "c32",
    channel: "whatsapp",
    preview: "Oke thanks Arma! Berguna banget.",
    time: "2h",
    unread: 0,
  },
  {
    id: "t33",
    contactId: "c33",
    channel: "whatsapp",
    preview: "Arma, stok Laura Mercier Translucent Powder kapan restocknya?",
    time: "3h",
    unread: 1,
  },
  {
    id: "t34",
    contactId: "c34",
    channel: "whatsapp",
    preview: "Perfect, aku save dulu ya Arma.",
    time: "Yesterday",
    unread: 0,
  },
  {
    id: "t35",
    contactId: "c35",
    channel: "whatsapp",
    preview: "Cara presentasi Dior Beauty ke customer baru yang belum familiar gimana?",
    time: "Yesterday",
    unread: 2,
  },
  {
    id: "t36",
    contactId: "c36",
    channel: "whatsapp",
    preview: "Arma ada SOP untuk handling retur produk Sisley di store?",
    time: "2d",
    unread: 0,
  },
  {
    id: "t37",
    contactId: "c37",
    channel: "whatsapp",
    preview: "Noted Arma, makasih infonya!",
    time: "2d",
    unread: 0,
  },
  {
    id: "t38",
    contactId: "c38",
    channel: "whatsapp",
    preview: "Cara demo aplikasi bareMinerals yang bener ke customer gimana?",
    time: "3d",
    unread: 0,
  },
  {
    id: "t28",
    contactId: "c28",
    channel: "whatsapp",
    preview: "Arma, bedanya Laura Mercier Loose vs Pressed Setting Powder apa ya?",
    time: "Yesterday",
    unread: 1,
  },
  {
    id: "t30",
    contactId: "c30",
    channel: "whatsapp",
    preview: "Arma, ada promo bundling Dior x Sisley ga bulan ini?",
    time: "2d",
    unread: 0,
  },
];

export type Template = {
  id: string;
  name: string;
  category: "Marketing" | "Utility" | "Service" | "Reminder";
  channel: Channel;
  status: "Approved" | "Pending" | "Rejected" | "Draft";
  updated: string;
  body: string;
  groupId?: string;
  language?: string;
  rejectionReason?: string;
  promoCodeId?: string;
};

export type TemplateGroup = {
  id: string;
  name: string;
  color: "indigo" | "pink" | "emerald" | "amber" | "sky" | "violet" | "slate" | "rose";
};

export const initialTemplateGroups: TemplateGroup[] = [
  { id: "tg-promotions", name: "Promotions", color: "pink" },
  { id: "tg-loyalty", name: "Beauty Club", color: "amber" },
  { id: "tg-cs", name: "Customer Service", color: "sky" },
  { id: "tg-events", name: "Events", color: "violet" },
  { id: "tg-launches", name: "SKU Launches", color: "indigo" },
  { id: "tg-leadnurture", name: "Lead Nurturing", color: "emerald" },
  { id: "tg-transactional", name: "Transactional", color: "slate" },
];

export const TEMPLATE_LANGUAGES = [
  { code: "id_ID", name: "Indonesian" },
  { code: "en_US", name: "English (US)" },
  { code: "en_GB", name: "English (UK)" },
] as const;

export const templates: Template[] = [
  {
    id: "tp1",
    name: "Velvet Rouge Launch",
    category: "Marketing",
    channel: "whatsapp",
    status: "Approved",
    updated: "2h ago",
    body: "Hi {{1}}, koleksi Velvet Rouge baru saja launching! VIP Beauty Club dapat akses 24 jam lebih awal — tap untuk belanja.",
    groupId: "tg-promotions",
    language: "id_ID",
  },
  {
    id: "tp2",
    name: "Order Shipped",
    category: "Utility",
    channel: "whatsapp",
    status: "Approved",
    updated: "1d ago",
    body: "Order kamu {{1}} sudah dikirim. Lacak di sini: {{2}}",
    groupId: "tg-transactional",
    language: "id_ID",
  },
  {
    id: "tp3",
    name: "Cart Reminder",
    category: "Marketing",
    channel: "whatsapp",
    status: "Approved",
    updated: "3d ago",
    body: "Hi {{1}}, cart kamu masih nunggu. Kami hold {{2}} untuk 24 jam ke depan.",
    groupId: "tg-promotions",
    language: "id_ID",
  },
  {
    id: "tp4",
    name: "Reminder Beauty Class",
    category: "Reminder",
    channel: "whatsapp",
    status: "Approved",
    updated: "1w ago",
    body: "Reminder: kelas makeup kamu besok jam {{1}} bersama {{2}}.",
    groupId: "tg-events",
    language: "id_ID",
  },
  {
    id: "tp5",
    name: "Ticket Follow-up",
    category: "Service",
    channel: "whatsapp",
    status: "Pending",
    updated: "5h ago",
    body: "Hi {{1}}, kami follow-up tiket #{{2}}. Sudah teratasi?",
    groupId: "tg-cs",
    language: "id_ID",
  },
  {
    id: "tp6",
    name: "Beauty Club Upgrade",
    category: "Marketing",
    channel: "whatsapp",
    status: "Draft",
    updated: "30m ago",
    body: "Selamat {{1}}! Kamu naik ke tier Platinum. Berikut benefit baru untukmu.",
    groupId: "tg-loyalty",
    language: "id_ID",
  },
  {
    id: "tp7",
    name: "Restock Alert",
    category: "Utility",
    channel: "whatsapp",
    status: "Approved",
    updated: "2w ago",
    body: "{{1}} yang kamu wishlist sudah ready stock lagi. Tap untuk order.",
    groupId: "tg-transactional",
    language: "id_ID",
  },
  {
    id: "tp8",
    name: "Payment Failed",
    category: "Service",
    channel: "whatsapp",
    status: "Pending",
    updated: "6h ago",
    body: "Halo {{1}} — pembayaran order {{2}} gagal. Coba lagi di sini.",
    groupId: "tg-cs",
    language: "id_ID",
  },
  {
    id: "tp9",
    name: "Flash Sale",
    category: "Marketing",
    channel: "whatsapp",
    status: "Rejected",
    updated: "1d ago",
    body: "🔥 FLASH SALE {{1}}! DISKON 80% SEMUA PRODUK — KLIK SEKARANG!",
    groupId: "tg-promotions",
    language: "id_ID",
    rejectionReason:
      "Content uses all-caps and excessive promotional language, which violates WhatsApp Business policy.",
  },
];

export type Broadcast = {
  id: string;
  name: string;
  channel: Channel;
  audience: string;
  reach: number;
  delivered: number;
  read: number;
  clicks: number;
  sentAt: string;
  /** Real ISO date (YYYY-MM-DD) — only set for "Sent" broadcasts, used to filter Overview metrics by date range. */
  sentAtDate?: string;
  status: "Sent" | "Scheduled" | "Draft";
  channelId?: string;
  listIds?: string[];
  totalAudience?: number;
  sendMode?: "now" | "schedule";
  scheduleDate?: string;
  scheduleTime?: string;
  createdBy?: string;
  createdAt?: string;
  contentMode?: "template" | "manual";
  templateId?: string;
  body?: string;
  footer?: string;
  buttons?: { label: string; kind: "quick_reply" | "url" | "phone" }[];
  replied?: number;
  failed?: number;
};

export const broadcasts: Broadcast[] = [
  {
    id: "b1",
    name: "Velvet Rouge — VIP Early Access",
    channel: "whatsapp",
    audience: "VIP · 12,408",
    reach: 12408,
    delivered: 12380,
    read: 11244,
    clicks: 4128,
    sentAt: "Today · 09:00",
    sentAtDate: "2026-07-30",
    status: "Sent",
    channelId: "wa-main",
    listIds: ["ls-vip", "ls-launch"],
    totalAudience: 12408,
    sendMode: "now",
    createdBy: "Putri Anggraini",
    createdAt: "Today · 08:42",
    contentMode: "template",
    templateId: "tp1",
    body: "Hi {{name}}, koleksi Velvet Rouge baru saja launching! VIP dapat akses 24 jam lebih awal.",
    footer: "Balas STOP untuk berhenti.",
    buttons: [{ label: "Belanja sekarang", kind: "url" }],
    replied: 824,
    failed: 28,
  },
  {
    id: "b2",
    name: "Glow Serum — Reseller Promo",
    channel: "whatsapp",
    audience: "Reseller · 4,910",
    reach: 4910,
    delivered: 4880,
    read: 4112,
    clicks: 1342,
    sentAt: "Yesterday",
    sentAtDate: "2026-07-29",
    status: "Sent",
    channelId: "wa-bdg",
    listIds: ["ls-launch"],
    totalAudience: 4910,
    sendMode: "now",
    createdBy: "Bagus Pratama",
    createdAt: "Yesterday · 17:10",
    contentMode: "template",
    templateId: "tp3",
    body: "Hi {{name}}, harga reseller Glow Serum bulan ini turun. Order minimum 24 pcs.",
    footer: "Aroma Abadi",
    buttons: [{ label: "Lihat katalog", kind: "url" }],
    replied: 312,
    failed: 30,
  },
  {
    id: "b3",
    name: "Promo Ramadhan Glow Set",
    channel: "whatsapp",
    audience: "All Contacts · 84,221",
    reach: 84221,
    delivered: 0,
    read: 0,
    clicks: 0,
    sentAt: "Fri · 08:00",
    status: "Scheduled",
    channelId: "wa-main",
    listIds: ["ls-community", "ls-launch"],
    totalAudience: 84221,
    sendMode: "schedule",
    scheduleDate: "2026-06-26",
    scheduleTime: "08:00",
    createdBy: "Putri Anggraini",
    createdAt: "2 days ago",
    contentMode: "manual",
    body: "Hi {{name}} — Promo Ramadhan Glow Set mulai Jumat jam 8 pagi. Akses awal untuk Beauty Club.",
    footer: "Balas STOP untuk berhenti.",
    buttons: [{ label: "Preview drop", kind: "url" }],
    replied: 0,
    failed: 0,
  },
  {
    id: "b4",
    name: "Corporate Hampers Lebaran",
    channel: "whatsapp",
    audience: "Corporate · 612",
    reach: 612,
    delivered: 610,
    read: 588,
    clicks: 244,
    sentAt: "3 days ago",
    sentAtDate: "2026-07-27",
    status: "Sent",
    channelId: "wa-jkt",
    listIds: ["ls-vip"],
    totalAudience: 612,
    sendMode: "now",
    createdBy: "Siti Rahmawati",
    createdAt: "3 days ago",
    contentMode: "template",
    templateId: "tp2",
    body: "Hi {{name}}, katalog hampers Lebaran corporate kamu sudah siap. Harga bulk terlampir.",
    buttons: [{ label: "Download katalog", kind: "url" }],
    replied: 48,
    failed: 2,
  },
  {
    id: "b5",
    name: "Beauty Club Tier Refresh",
    channel: "whatsapp",
    audience: "Active Customers · 22,114",
    reach: 22114,
    delivered: 0,
    read: 0,
    clicks: 0,
    sentAt: "—",
    status: "Draft",
    channelId: "wa-main",
    listIds: ["ls-community"],
    totalAudience: 22114,
    sendMode: "now",
    createdBy: "Indah Permata",
    createdAt: "30 minutes ago",
    contentMode: "template",
    templateId: "tp6",
    body: "Selamat {{name}}! Kamu naik ke tier Beauty Club berikutnya. Berikut benefit baru untukmu.",
    buttons: [{ label: "Lihat benefit", kind: "url" }],
    replied: 0,
    failed: 0,
  },
];

// Charts (WhatsApp-only)
export const volumeSeries = [
  { d: "Sen", whatsapp: 4200 },
  { d: "Sel", whatsapp: 5120 },
  { d: "Rab", whatsapp: 4880 },
  { d: "Kam", whatsapp: 6020 },
  { d: "Jum", whatsapp: 7240 },
  { d: "Sab", whatsapp: 5410 },
  { d: "Min", whatsapp: 4980 },
];

export const channelPerf = [{ name: "WhatsApp", value: 100 }];

export const contactGrowth = [
  { m: "Jun", v: 12400 },
  { m: "Jul", v: 14820 },
  { m: "Agu", v: 16210 },
  { m: "Sep", v: 18540 },
  { m: "Okt", v: 21810 },
  { m: "Nov", v: 26120 },
  { m: "Des", v: 29840 },
];

export const recentActivity = [
  {
    id: "a0",
    icon: "alert",
    text: 'Event "Aroma Abadi Beauty Class" successfully scheduled — 87 contacts registered',
    time: "Just now",
  },
  {
    id: "a1",
    icon: "send",
    text: 'Broadcast "Velvet Rouge — VIP Early Access" sent to 12,380 contacts',
    time: "2m ago",
  },
  {
    id: "a2",
    icon: "user",
    text: "Siti Rahmawati tagged as VIP by Putri Anggraini",
    time: "14m ago",
  },
  {
    id: "a3",
    icon: "msg",
    text: 'Template "Beauty Club Upgrade" submitted for review',
    time: "32m ago",
  },
  {
    id: "a4",
    icon: "alert",
    text: "WhatsApp channel quality rating increased to High",
    time: "1h ago",
  },
  { id: "a5", icon: "user", text: "47 new contacts imported from POS sync", time: "2h ago" },
];

export type ConnectedChannel = {
  id: string;
  channel: Channel;
  name: string;
  handle: string;
  status: "connected" | "disconnected";
};

export const connectedChannels: ConnectedChannel[] = [
  {
    id: "wa-main",
    channel: "whatsapp",
    name: "Arma by Aroma Abadi",
    handle: "+62 811 9001 2233",
    status: "connected",
  },
];
