/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InviteMembersRouteImport } from './routes/invite-members'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as BroadcastsIndexRouteImport } from './routes/broadcasts.index'
import { Route as TemplatesNewRouteImport } from './routes/templates.new'
import { Route as ContactsNewRouteImport } from './routes/contacts.new'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as BroadcastsNewRouteImport } from './routes/broadcasts.new'
import { Route as BroadcastsBroadcastIdRouteImport } from './routes/broadcasts.$broadcastId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteMembersRoute = InviteMembersRouteImport.update({
  id: '/invite-members',
  path: '/invite-members',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsIndexRoute = BroadcastsIndexRouteImport.update({
  id: '/broadcasts/',
  path: '/broadcasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContactsRoute,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ContactsRoute,
} as any)
const BroadcastsNewRoute = BroadcastsNewRouteImport.update({
  id: '/broadcasts/new',
  path: '/broadcasts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsBroadcastIdRoute = BroadcastsBroadcastIdRouteImport.update({
  id: '/broadcasts/$broadcastId',
  path: '/broadcasts/$broadcastId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/invite-members': typeof InviteMembersRoute
  '/settings': typeof SettingsRoute
  '/broadcasts/$broadcastId': typeof BroadcastsBroadcastIdRoute
  '/broadcasts/new': typeof BroadcastsNewRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/broadcasts/': typeof BroadcastsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/invite-members': typeof InviteMembersRoute
  '/settings': typeof SettingsRoute
  '/broadcasts/$broadcastId': typeof BroadcastsBroadcastIdRoute
  '/broadcasts/new': typeof BroadcastsNewRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/broadcasts': typeof BroadcastsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/invite-members': typeof InviteMembersRoute
  '/settings': typeof SettingsRoute
  '/broadcasts/$broadcastId': typeof BroadcastsBroadcastIdRoute
  '/broadcasts/new': typeof BroadcastsNewRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/broadcasts/': typeof BroadcastsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/inbox'
    | '/invite-members'
    | '/settings'
    | '/broadcasts/$broadcastId'
    | '/broadcasts/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/templates/new'
    | '/broadcasts/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/inbox'
    | '/invite-members'
    | '/settings'
    | '/broadcasts/$broadcastId'
    | '/broadcasts/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/templates/new'
    | '/broadcasts'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/inbox'
    | '/invite-members'
    | '/settings'
    | '/broadcasts/$broadcastId'
    | '/broadcasts/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/templates/new'
    | '/broadcasts/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  InboxRoute: typeof InboxRoute
  InviteMembersRoute: typeof InviteMembersRoute
  SettingsRoute: typeof SettingsRoute
  BroadcastsBroadcastIdRoute: typeof BroadcastsBroadcastIdRoute
  BroadcastsNewRoute: typeof BroadcastsNewRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  BroadcastsIndexRoute: typeof BroadcastsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-members': {
      id: '/invite-members'
      path: '/invite-members'
      fullPath: '/invite-members'
      preLoaderRoute: typeof InviteMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts/': {
      id: '/broadcasts/'
      path: '/broadcasts'
      fullPath: '/broadcasts/'
      preLoaderRoute: typeof BroadcastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/broadcasts/new': {
      id: '/broadcasts/new'
      path: '/broadcasts/new'
      fullPath: '/broadcasts/new'
      preLoaderRoute: typeof BroadcastsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts/$broadcastId': {
      id: '/broadcasts/$broadcastId'
      path: '/broadcasts/$broadcastId'
      fullPath: '/broadcasts/$broadcastId'
      preLoaderRoute: typeof BroadcastsBroadcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContactsRouteChildren {
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsNewRoute: typeof ContactsNewRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsNewRoute: ContactsNewRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRouteWithChildren,
  InboxRoute: InboxRoute,
  InviteMembersRoute: InviteMembersRoute,
  SettingsRoute: SettingsRoute,
  BroadcastsBroadcastIdRoute: BroadcastsBroadcastIdRoute,
  BroadcastsNewRoute: BroadcastsNewRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  BroadcastsIndexRoute: BroadcastsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
